Adding PromptLayer support of tags
BerriAI/litellm pull request #1491
Opened 2024-01-18 09:09 UTC by samyxdev

Hi everyone,

I noticed that LiteLLM doesn't support the `pl_tags` argument of the [PromptLayer Python API](https://docs.promptlayer.com/languages/python), only `metadata` is supported for now. In this PR, I propose to add the support of such tags by adding them to the `metadata` argument.

Here is a working example with tags and metadata:
`
        response = completion(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": "Hi 👋 - i'm ai21"}],
            temperature=0.2,
            max_tokens=20,
            metadata={"model": "ai21", "pl_tags": ["env:dev"]},
        )
`

I also added a test to ensure the support of tags.

**Note**:
I thought about adding the `pl_tags` argument by itself (i.e. not in `metadata`) but it seems that LiteLLM is adding every extra argument as an `extra_body` argument for OpenAI and Azure, which then leads to errors as the latter providers don't recognize this extra `pl_tags` argument: https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L4072

2024-01-19 23:20 UTC, ishaan-jaff requested changes
Requested 1 change, can you send a screenshot of this logging working on Promptlayer

2024-01-19 23:20 UTC, ishaan-jaff commented on litellm/tests/test_promptlayer_integration.py
> +        )
LGTM, can you set `mock_response="some text"` so it doesn't make the OpenAI API call for this test

2024-01-21 21:41 UTC, samyxdev commented
Thanks for the feedback @ishaan-jaff. I just realized a few issues in the test and PromptLayer integrations:

- Tests are not handled properly here, as pytest will consider these tests as passing even though they are actually failing, as the top try-catch block isn't raising any exceptions. I would recommend avoiding the double try-catch and go for a regular assertion or going with a `pytest.fail(f"Error occurred: {e}")` as observed in some of other tests, instead of a `print(e)`.
- PromptLayer integration is considering the call as succeding even though it didn't. Here is a self-explanatory example of logging output: `Prompt Layer Logging: success - final response object: {"message":"No PromptLayer API key provided","success":false}`

2024-02-20 09:11 UTC, samyxdev commented
Hello @ishaan-jaff, do you see any other blockers ?

2024-02-20 16:45 UTC, ishaan-jaff commented
Hi @samyxdev will review this today

2024-02-22 19:42 UTC, merged