fix langchain cost
BerriAI/litellm pull request #1737
Opened 2024-02-01 15:36 UTC by maxdeichmann

2024-02-01 15:47 UTC, ishaan-jaff requested changes

2024-02-01 15:47 UTC, ishaan-jaff commented on litellm/tests/test_alangfuse.py
> -def test_langfuse_logging_async():
we cannot remove this test it would impact prod users

2024-02-01 16:34 UTC, krrishdholakia commented
lgtm - pending ishaan's callouts @maxdeichmann

2024-02-02 08:29 UTC, maxdeichmann commented
Sorry, this did not really change something

2024-02-02 08:29 UTC, closed without merging