Update helm chart to accomodate recent project changes
BerriAI/litellm pull request #2145
Opened 2024-02-23 01:58 UTC by ShaunMaher

* Remove the `--run_gunicorn ` startup flag
* Tidy up some helm chart build edge cases (i.e. can't increment version if there is no previous version)
* Update build process to use the new chart name (`-helm` suffix removed).  Thanks to @Lunik for forcing me to reevaluate my previous assumption about the helm chart name conflicting with the image name.  It seems that it "just works".
* Integrate helm chart build process into the process that builds the docker images so that this becomes a single step (#2040)
* Tweak the GitHub workflow that builds the docker images so it only tries to push to docker hub if the project running the build is `BerriAI/litellm`.  This allows other developers to fork this repository and test the workflows on their forks, without them always failing because they (obviously) can't push to docker hub as BerriAI.
* This should also close the deployment parts of #1880, but mainly because @Lunik's work on #2018

2024-02-23 02:00 UTC, ishaan-jaff commented
cc@Lunik can we get your feedback on this too - since you use this ?

2024-03-09 20:47 UTC, debdutdeb commented
Would be amazing to have this merged  🙏🏼  I'd rather not copy the whole stuff to another chart to use as dependency. 

Please let me know if I can help. 

From the looks of it, structurally it looks all good, but I've not looked deep in.

2024-03-09 21:18 UTC, ishaan-jaff commented
@debdutdeb it would help us if you could check if this helm chart works for you ?

2024-03-12 14:58 UTC, ishaan-jaff requested changes
re `run_gunicorn`

2024-03-12 14:58 UTC, ishaan-jaff commented on deploy/charts/litellm/templates/deployment.yaml
> -            - --run_gunicorn
why remove this ?

2024-03-16 16:48 UTC, ishaan-jaff commented
working on getting these changes merged now !

2024-03-16 17:28 UTC, ishaan-jaff commented
Update I took these changes and added it to main, confirmed it works. We needed to rename the chart to `litellm-helm` since it would overwrite the litellm docker image 

I'm going to still merge this PR and then re-apply my changes. Want to make sure I recognize @ShaunMaher's work on our contributors list + release notes !

2024-03-16 17:50 UTC, merged