[Bug]: litellm proxy cli may log db credentials
BerriAI/litellm pull request #2583
Opened 2024-03-19 09:29 UTC by CheeseDurger

Database url can contain the db user credentials. For instance: `postgresql://user:password@server:port/...`

Hence, it seems better not to log this url.

2024-03-21 14:22 UTC, ishaan-jaff requested changes
change requested @CheeseDurger

2024-03-21 14:22 UTC, ishaan-jaff commented on litellm/proxy/proxy_cli.py
> -    print(f"params: {params}")
This helps users with debugging. Instead of removing it can we add `******` for first couple chars. Since the first couple chars contain the password

2024-03-21 14:23 UTC, ishaan-jaff commented
@CheeseDurger do you use LiteLLM Proxy today ? I'd love to get your feedback over call. My calendly for your convenience:
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03

2024-03-21 16:59 UTC, krrishdholakia commented
bump on this? @CheeseDurger

2024-03-28 15:44 UTC, CheeseDurger commented
Why not using the `DEBUG` variable then? Do you have another example of debug logging somewhere?

2024-06-07 19:49 UTC, ishaan-jaff commented
@CheeseDurger open to merging this if you change them to debug statements

2024-06-09 07:46 UTC, closed without merging