add vertex_ai/text-embedding-preview-0409
BerriAI/litellm pull request #2999
Opened 2024-04-13 07:32 UTC by Dev-Khant

Solves #2916.

2024-04-14 22:05 UTC, widike commented
This would be very helpful to have.

2024-04-15 01:44 UTC, Dev-Khant commented
@krrishdholakia @ishaan-jaff Can you please review this? Thanks.

2024-04-15 14:43 UTC, ishaan-jaff requested changes
Is this all that's required @Dev-Khant ? Can you send a screenshot of this working for you locally ?

2024-04-15 21:43 UTC, krrishdholakia commented on litellm/model_prices_and_context_window_backup.json
> +        "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models"
@Dev-Khant the source is incorrect here - i don't see `text-embedding-preview-0409` on https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models

Can you please link the source you got the pricing information from 


Also - is the output vector size only 768? On the example here I see 256 - https://cloud.google.com/blog/products/ai-machine-learning/google-cloud-announces-new-text-embedding-models

2024-04-15 23:09 UTC, widike commented on litellm/model_prices_and_context_window_backup.json
> +        "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models"
The model names for embeddings are correct. See here:
- https://cloud.google.com/blog/products/ai-machine-learning/google-cloud-announces-new-text-embedding-models
- https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings

2024-04-15 23:51 UTC, krrishdholakia commented on litellm/model_prices_and_context_window_backup.json
> +        "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models"
hey @demux79 thanks - do you have a link to the pricing for this too?

2024-04-15 23:54 UTC, ghost commented on litellm/model_prices_and_context_window_backup.json
> +        "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models"
is it this? https://cloud.google.com/vertex-ai/generative-ai/pricing

the cost of a multimodal embeddings api 
<img width="1057" alt="Screenshot 2024-04-15 at 4 53 53 PM" src="https://github.com/BerriAI/litellm/assets/17561003/199b90c3-a628-4c11-b8cd-6df25d9dc3ca">

2024-04-16 07:40 UTC, widike commented on litellm/model_prices_and_context_window_backup.json
> +        "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models"
The first link also contains the pricing, right above "Dynamic embedding dimensions" (256 vs 768):

The pricing for our text embedding models is $0.000025/1,000 characters for [online requests](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings#latest_models) and $0.00002/1,000 characters for [batch requests](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/batch-prediction-genai-embeddings).

2024-04-16 14:03 UTC, krrishdholakia commented on litellm/model_prices_and_context_window_backup.json
> +        "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#foundation_models"
ok - merging. will fix this on our end.

2024-04-16 14:03 UTC, merged