fix(build): .dockerignore not picked up
BerriAI/litellm pull request #3116
Opened 2024-04-18 08:59 UTC by bcvanmeurs

#2982 did not solve the issue, the files are still in the image builds.

Did some more research and found out that using the git context of the build-push-action ignores the .dockerignore because it is pulled by buildkit. Instead it is recommended to use the checkout action together with the path context.

See https://github.com/docker/build-push-action?tab=readme-ov-file#git-context and https://github.com/docker/build-push-action?tab=readme-ov-file#path-context.

Also https://github.com/docker/build-push-action/issues/655

2024-04-18 18:19 UTC, ishaan-jaff requested changes
we need the context to pin to a commit hash

2024-04-18 18:19 UTC, ishaan-jaff commented on .github/workflows/ghcr_deploy.yml
> +          context: .
this would break our releases - we need the context to pin to a commit hash

2024-04-18 18:39 UTC, bcvanmeurs commented on .github/workflows/ghcr_deploy.yml
> +          context: .
Ah of course! 

I added the commit hash input to the checkout step. I think this should be equivalent, but it is hard to test without actually running it.

2024-05-07 13:27 UTC, bcvanmeurs commented
@ishaan-jaff could you have a second look at this PR please?

2024-06-15 16:14 UTC, ishaan-jaff commented
merging this - will take care of issues that come up

2024-06-15 16:15 UTC, merged