[Feature] Add cache to disk
BerriAI/litellm pull request #3266
Opened 2024-04-24 14:06 UTC by antonioloison

resolves #3092. 

Added disk cache using the `diskcache` module.

Please check the issue for more context.

2024-05-07 15:13 UTC, ishaan-jaff requested changes

2024-05-07 15:13 UTC, ishaan-jaff commented on litellm/tests/test_caching.py
> +    response1 = completion(
can you use `mock_response` here so it does not make the LLM API call 

if you look up `mock_response` you'll see how it;s used through the testing pipeline

2024-05-07 15:13 UTC, ishaan-jaff commented on litellm/caching.py
> +import diskcache as dc
can this not be imported here, instead please import it inside the `DiskCache` class

2024-05-07 15:13 UTC, ishaan-jaff commented on litellm/caching.py
> +import diskcache as dc
We don't want this impacting users on litellm proxy server

2024-05-07 15:14 UTC, ishaan-jaff commented on litellm/caching.py
> +import diskcache as dc
since this is an optional dependency it should only be imported in the class

2024-05-07 15:14 UTC, ishaan-jaff requested changes
left review, can you please add this to docs too. Thanks

2024-05-10 10:19 UTC, antonioloison commented on litellm/tests/test_caching.py
> +    response1 = completion(
done, you can resolve the conversation if you think it is correct

2024-05-10 10:36 UTC, antonioloison commented on litellm/caching.py
> +import diskcache as dc
I understand, I moved it to the class.
I removed the diskcache dependency from the `pyproject.toml` file and added the install command in the docs in the same way as the `s3-cache`.

2024-05-10 10:38 UTC, antonioloison commented
> left review, can you please add this to docs too. Thanks

I added the doc for the disk cache and corrected the arguments of the `add_cache`, `update_cache`... functions.
I also changed the name of the file `redis_cache.md` to `all_caches.md` as it no longer only concerns the redis cache.

2024-05-14 16:23 UTC, ishaan-jaff approved these changes

2024-05-14 16:24 UTC, merged