fix optional_params for mistral
BerriAI/litellm pull request #3305
Opened 2024-04-25 19:32 UTC by bpoppinga

While using the mistral ai api through litellm, we noticed that some parameters are not passed correctly:

1. Even though `response_format` is listed as a parameter for mistral in `get_supported_openai_params`, it is not being transferred to `optional_params`.
2. `random_seed` is stored in `optional_params["extra_body"]`, but later `optional_params["extra_body"]` is overwritten by an empty dictionary towards the end of the function.

I am not fully familiar with the overall logic yet, but as far as I know, addressing these points should resolve both problems. If it introduces new issues, please let me know.

2024-04-25 19:40 UTC, ishaan-jaff requested changes
please can we add some testing to ensure there are no regressions on this in the future

2024-04-25 19:41 UTC, ishaan-jaff commented
@bpoppinga perhaps you can add tests to `test_optional_params.py`

2024-04-26 01:13 UTC, krrishdholakia commented
hey @bpoppinga can you share a sample call to repro the problem?

2024-04-26 01:20 UTC, krrishdholakia commented
just looked through the logic - i don't think we need this in _map_and_modify() 

you just need to add it in the mistral if block of optional_params

2024-04-26 01:32 UTC, krrishdholakia commented
support added. can confirm this works as well - https://github.com/BerriAI/litellm/commit/86a3d24d75d28ca0777fb568b6f2e63436028b73

2024-04-26 01:32 UTC, closed without merging