add_function_to_prompt bug fix
BerriAI/litellm pull request #3439
Opened 2024-05-04 03:39 UTC by phact

This blows up when there's no "functions" in the dictionary even when tools is present because the inner function executes regardless (does not short circuit).

2024-05-04 18:16 UTC, ishaan-jaff requested changes
@phact thanks for the PR, can you please add a unit test for this before we merge

2024-05-07 17:25 UTC, phact commented
Added unit test [and uncovered another bug]

Thanks!

2024-05-07 18:08 UTC, phact commented
I'm hitting `RuntimeError('dictionary changed size during iteration')` in some cases, is wrapping

>          for k in passed_params.keys():

 in `list()` the right fix?

2024-05-07 18:28 UTC, phact commented
Hmm this situation reproduces on `main` with the existing cohere unit test -- test_cohere_completion:

```

test_cohere_completion.py:20 (test_chat_completion_cohere)
def test_chat_completion_cohere():
        try:
            litellm.set_verbose = True
            messages = [
                {
                    "role": "user",
                    "content": "Hey",
                },
            ]
>           response = completion(
                model="cohere_chat/command-r",
                messages=messages,
                max_tokens=10,
            )

test_cohere_completion.py:30: 
```

```
                    extra_body[k] = passed_params[k]
            optional_params["extra_body"] = extra_body
        else:
            # if user passed in non-default kwargs for specific providers/models, pass them along
>           for k in passed_params.keys():
E           RuntimeError: dictionary changed size during iteration

../utils.py:5772: RuntimeError

During handling of the above exception, another exception occurred:

    def test_chat_completion_cohere_tool_calling():
        try:
            litellm.set_verbose = True
            messages = [
                {
                    "role": "user",
                    "content": "What is the weather like in Boston?",
                },
            ]
            response = completion(
                model="cohere_chat/command-r",
                messages=messages,
                tools=[
                    {
                        "type": "function",
                        "function": {
                            "name": "get_current_weather",
                            "description": "Get the current weather in a given location",
                            "parameters": {
                                "type": "object",
                                "properties": {
                                    "location": {
                                        "type": "string",
                                        "description": "The city and state, e.g. San Francisco, CA",
                                    },
                                    "unit": {
                                        "type": "string",
                                        "enum": ["celsius", "fahrenheit"],
                                    },
                                },
                                "required": ["location"],
                            },
                        },
                    }
                ],
            )
            print(response)
        except Exception as e:
>           pytest.fail(f"Error occurred: {e}")
E           Failed: Error occurred: dictionary changed size during iteration

test_cohere_completion.py:100: Failed
``` 

Do these get run in CI anywhere?

2024-05-07 18:38 UTC, phact commented
>    passed_params = locals().copy()

seems to fix it but `locals()` is used all over the code base, wondering if this is going to lead to similar issues elsewhere.

2024-05-07 19:06 UTC, phact commented
Tested this locally and it looks good. 

@ishaan-jaff from what I can tell this is affecting completions that use `tools` for every model including `openai`.

Can we cut a release?

2024-05-07 19:17 UTC, ishaan-jaff commented
> from what I can tell this is affecting completions that use tools for every model including openai 

what exactly is the issue you would see on OpenAI + tool usage ?

2024-05-07 19:18 UTC, phact commented
> E           Failed: Error occurred: dictionary changed size during iteration

2024-05-07 19:31 UTC, phact commented
I'll try to repro in a unit test

2024-05-07 19:33 UTC, ishaan-jaff commented
> 'll try to repro in a unit test

would be great if you could add this test in this PR too thanks @phact

2024-05-08 02:28 UTC, ishaan-jaff approved these changes
lgtm

2024-05-08 02:31 UTC, merged

2024-05-08 10:44 UTC, phact commented
Ran out of time yesterday, I'll look into adding a test in a new PR when I get a chance.