Add return_exceptions to batch_completion (retry)
BerriAI/litellm pull request #3462
Opened 2024-05-05 05:34 UTC by ffreemt

Refer to https://github.com/BerriAI/litellm/pull/3397.

Samepl code and screenshot to show it works locally with and without setting return_exceptions.

1.  without setting return_exception (or setting to False): it throws an exception, exactly as what litellm behaves without this modification.
2.  with return_exception   setting to True, bacth_completion won't  exceptions, exceptions if any are returned instead.

```
# litellm-rundown.py
import litellm
msg1 = [{"role": "user", "content": "hi 1"}]
msg2 = [{"role": "user", "content": "hi 2"}]

if "res" in globals():
  del res
try:
  res = litellm.batch_completion(
      model="gpt-3.5-turbo",
      messages=[msg1, msg2],
      api_key="sk_xyz",  # deliberately set invalid key
      # return_exceptions=False,
  )
except Exception as exc:
  # res not defined
  print("*** 1>>>", "res" in globals(), exc)

res = litellm.batch_completion(
    model="gpt-3.5-turbo",
    messages=[msg1, msg2],
    api_key="sk_xyz",  # deliberately set invalid key
    return_exceptions=True,
)

# res defined, exceptions returned to res
print("**** 2>>>", "res" in globals())

print(isinstance(res[0], litellm.exceptions.AuthenticationError), isinstance(res[1], litellm.exceptions.AuthenticationError))

```

Sample runs showing batch completions working locally with and without setting return_exceptions

![litellm-run-Screenshot 2024-05-05 130545](https://github.com/BerriAI/litellm/assets/52522252/355d67f8-02fd-40eb-907f-6b94d18325ca)

i actually need this in a usecase. Thanks a lot for merging if possible.

2024-05-23 23:44 UTC, ishaan-jaff requested changes
can we actually make this default behavior @ffreemt 

no need to hide this behind `return_exceptions`

2024-05-24 03:25 UTC, ffreemt commented
I made  return-exceptions as default behavior  @ishaan-jaff 

I also removed a redundant test (test_batch_completion_return_exceptions_default()) in litellm/litellm/tests/test_batch_completion_return_exceptions.py since batch_completion will no longer raise any exception.

2024-05-24 16:19 UTC, ishaan-jaff approved these changes

2024-05-24 16:19 UTC, merged

2024-06-01 17:41 UTC, ishaan-jaff commented
hi @ffreemt  can we hop on a call sometime this week. I'd love to learn how we can improve litellm for you. What's the best email to send an invite to ?

If it's easier here's a link to my cal https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat