Add IAM cred caching for OIDC flow
BerriAI/litellm pull request #3712
Opened 2024-05-17 21:35 UTC by Manouchehri

## Title

This should improve the perf, as this allows avoiding making an extra call to STS on every invocation of Bedrock. 

Should be merged after #3688. Doing this as a separate PR in case you don't like my caching method; I don't want this PR to slow down #3688 from being merged.

## Type

🆕 New Feature

## Changes

Just uses DualCache to speed things up!

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

I ran the same request multiple times, and could see the cache being used in LiteLLM's logs. (It's kinda difficult to post a screenshot without including a lot of PII.)

<img width="713" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/350a33d9-9744-435a-8aaa-41eee75bfda4">

2024-05-27 16:22 UTC, krrishdholakia commented on litellm/llms/bedrock_httpx.py
> +                oidc_token = get_secret(aws_web_identity_token)
fixing this - https://github.com/BerriAI/litellm/issues/3858, is a precursor to this PR, since this would also introduce sync flows to an async call

2024-05-27 16:22 UTC, krrishdholakia requested changes
https://github.com/BerriAI/litellm/issues/3858 blocks this pr

2024-06-01 01:49 UTC, krrishdholakia commented
@Manouchehri please can we add some testing for this? couple users use the sts flow and i want to make sure there's no regressions

2024-06-01 01:50 UTC, Manouchehri commented on litellm/llms/bedrock_httpx.py
> +                )
Note for tomorrow David: this need to have `endpoint_url=f"https://sts.{aws_region_name}.amazonaws.com"` as well, STS sorta ignores `region_name` it seems.

2024-06-01 02:07 UTC, Manouchehri commented
> @Manouchehri please can we add some testing for this? couple users use the sts flow and i want to make sure there's no regressions

Definitely, that's a good idea, I'll do. We sorta ish already test it, but it's more by luck and not intentional. 

Two questions: 

1. How can I validate that the cache is actually working and not just issuing a new token?
2. How can I allow LiteLLM to only do one STS call at once? There's no point in getting multiple tokens in parallel (it will be the same speed), it's just wasteful on resources and adds noise.

2024-06-01 04:09 UTC, Manouchehri commented on litellm/llms/bedrock_httpx.py
> +                )
Otherwise, boto3 oddly relies on us-east-1. Terrible design decision. https://github.com/boto/boto3/issues/1859#issuecomment-461622548

2024-06-01 15:35 UTC, Manouchehri commented on litellm/llms/bedrock_httpx.py
> +                oidc_token = get_secret(aws_web_identity_token)
Let's tackle this in a different PR, since this is purely focused on the Bedrock IAM part. (While #3858 mentions the host's OIDC token being sync.)

2024-06-01 15:41 UTC, Manouchehri commented
This shaves a lot of time off the current setup, between like 0.25 to 1 second per Bedrock call. :) 

The STS fix is also needed.

Ready for merging!

2024-06-05 17:39 UTC, Manouchehri commented
Bump on this? It's becoming a bit of a burden to maintain out-of-tree patches for weeks.

2024-06-11 15:48 UTC, krrishdholakia commented
hey @Manouchehri missed this - sorry for the delay on my end. 

Saw you made a couple changes - could you walk me through it?

2024-06-11 15:49 UTC, krrishdholakia commented
i'm also happy to hop on a call and help get all the oidc pr's done

2024-06-11 15:51 UTC, Manouchehri commented
> i'm also happy to hop on a call and help get all the oidc pr's done

Gimme a moment to finish testing this and #3861. =)

2024-06-11 16:21 UTC, Manouchehri commented
You free now?

2024-06-12 19:37 UTC, krrishdholakia commented on litellm/llms/bedrock_httpx.py
> +iam_cache = DualCache()
switch to in memory cache

2024-06-12 19:38 UTC, krrishdholakia commented on litellm/llms/bedrock_httpx.py
> +iam_cache = DualCache()
InMemoryCache - https://github.com/BerriAI/litellm/blob/fb96f07ccb28fffbfe7bd9e9723d48c16c4bb581/litellm/caching.py#L59

2024-06-12 19:39 UTC, krrishdholakia commented on litellm/llms/bedrock_httpx.py
> +                iam_cache.set_cache(key=iam_creds_cache_key, value=json.dumps(iam_creds_dict), ttl=3600 - 60)
can we have ttl be an enum at the top of the file, so it's easier to know

2024-06-12 19:42 UTC, krrishdholakia commented on litellm/llms/bedrock_httpx.py
> +        if aws_web_identity_token is not None and aws_role_name is not None and aws_session_name is not None:
can you add a comment explaining when you'd enter this flow

2024-06-12 19:44 UTC, merged

2024-06-13 01:28 UTC, Manouchehri commented
Self note: I can confirm that this is indeed working, I now only see one `AssumeRoleWithWebIdentity` event before multiple Bedrock calls. =) 

<img width="871" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/f1028aa2-3137-4885-88b3-49cd0fb2a4b5">

Previously (before this PR was merged), I had multiple `AssumeRoleWithWebIdentity` calls (one for each Bedrock invocation, which is waaaay too high of an overhead).

<img width="1004" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/3d8decdd-5d1a-4d0b-a19f-396f79a0bbc2">