feat: add langfuse metadata via proxy request headers
BerriAI/litellm pull request #3990
Opened 2024-06-03 20:25 UTC by ndrsfel

Hey all,

I am missing a small feature when using LiteLLM Proxy together with Langfuse. I am using the Vercel AI SDK and want to pass additional metadata to the proxy completion call. However, the `createOpenAi()` from [AI-SDK](https://sdk.vercel.ai/providers/ai-sdk-providers/openai) only supports custom metadata via headers out of the box.

For example, I initialize my trace via `const trace = langfuse.trace()` and pass the existing traceId to Langfuse via
```javascript
  const openai = createOpenAI({
    apiKey: process.env.OPENAI_API_KEY,
    baseURL: process.env.OPENAI_BASE_URL,
    headers: {
      "trace_trace_id": trace.id
    }
  });
```
because the traceId response from LiteLLM is also not easily accesible.

That's why I extended the Langfuse logger to accept `trace_*` keys and pass it over as `metadata` to the Langfuse logger.

Apparently I am not 100% familiar with all corner cases when extending the logger, but wanted to contribute this functionality back. I am open to adjust my changes to comply with your guidelines and to catch any corner cases.

Thanks a lot for this amazing library.

Cheers, Andreas ✌️

2024-06-05 20:45 UTC, ishaan-jaff requested changes
1 change + please add to langfuse docs

2024-06-05 20:45 UTC, ishaan-jaff commented on litellm/integrations/langfuse.py
> +            metadata = self.add_metadata_from_header(litellm_params)
this is confusing. Can you keep the line. Then after that line you can set `metadata = self.add_metadata_from_header(metadata)` 

```python
metadata = (
                litellm_params.get("metadata", {}) or {}
            )  
            
 ```

2024-06-06 06:08 UTC, ndrsfel commented
@ishaan-jaff renamed `trace_*` to `langfuse_*` prefix and added an example to langfuse documentation

2024-06-06 14:52 UTC, ishaan-jaff approved these changes

2024-06-06 14:52 UTC, merged