Clarifai-LiteLLM Addressed proxy issues
BerriAI/litellm pull request #4102
Opened 2024-06-10 18:35 UTC by mogith-pn

## Clarifai-LiteLLM Addressed proxy issues

## Relevant issues

* Fixes #3862 & #3769

## Type

🐛 Bug Fix
📖 Documentation

## Changes

* Modified Async completion function.
* Modified stream function.
* Addressed spelling mistakes in doc.

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes
![Screenshot 2024-06-10 at 11 59 41 PM](https://github.com/mogith-pn/litellm-fork/assets/143642606/5d8cd618-b0b4-4702-966e-700b97632097)

2024-06-10 18:36 UTC, mogith-pn commented
@ishaan-jaff  

Can you please take a look into this PR ? Thanks !

2024-06-10 21:28 UTC, krrishdholakia commented on litellm/llms/clarifai.py
> +        return asyncio.run(async_completion(
@mogith-pn can we please have this be actually async. 

Current approach will be a blocking call for users under high traffic.

2024-06-10 21:28 UTC, krrishdholakia commented on litellm/utils.py
> +                "is_finished": False,
please add testing for this change

2024-06-10 21:29 UTC, krrishdholakia requested changes
Please make the calls actually async and add testing for async completion + async streaming.

2024-06-13 00:10 UTC, ishaan-jaff commented
closing in favor of 
https://github.com/BerriAI/litellm/pull/4158

2024-06-13 00:10 UTC, closed without merging