fix issue to read vertex_credentials
BerriAI/litellm pull request #4199
Opened 2024-06-14 18:50 UTC by hawktang

## Title

Implement user authentication feature

fix issue to read vertex_credentials

## Relevant issues

fix issue to read vertex_credentials

## Type

🐛 Bug Fix

## Changes

```python
from litellm import completion
import os

# os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "sia-data-team-vertexai-gcp-key_new.json"

model = "claude-3-opus@20240229"

vertex_ai_project = "..." # can also set this as os.environ["VERTEXAI_PROJECT"]
vertex_ai_location = "us-east5" # can also set this as os.environ["VERTEXAI_LOCATION"]

response = completion(
    model="vertex_ai/" + model,
    messages=[{"role": "user", "content": "hi"}],
    temperature=0.7,
    vertex_ai_project=vertex_ai_project,
    vertex_ai_location=vertex_ai_location,
    vertex_ai_credentials =  "./vertexai-gcp-key_new.json"
)
print("\nModel Response", response)
```
VertexAIError: Expecting value: line 1 column 1 (char 0)

reference
https://google-auth.readthedocs.io/en/stable/reference/google.oauth2.service_account.html

```python
service_account_info = json.load(open('service_account.json'))
credentials = service_account.Credentials.from_service_account_info(
    service_account_info)
```
<img width="936" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/36233386-820b-4b1f-95e8-6d1f711b2406">
<img width="936" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/36233386-820b-4b1f-95e8-6d1f711b2406">
<img width="936" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/36233386-820b-4b1f-95e8-6d1f711b2406">

<img width="599" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/e2eb8978-6b3f-4758-b155-c612d45148fb">
<img width="599" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/e2eb8978-6b3f-4758-b155-c612d45148fb">
<img width="599" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/e2eb8978-6b3f-4758-b155-c612d45148fb">

json_obj = json.load(open(vertex_credentials))

## [REQUIRED] Testing - Attach a screenshot of any new tests passing local

change code, rerun script

2024-06-14 21:23 UTC, krrishdholakia requested changes

2024-06-14 21:23 UTC, krrishdholakia commented on litellm/llms/vertex_ai_anthropic.py
> +                json_obj = json.load(open(vertex_credentials))
hey @hawktang this assumes the vertex_credentials is a filepath 

That's not the intended purpose of this code block. It's a json str of the vertex_credentials 

I believe we can support both flows - can you change this to check if it's a filepath or json string and proceed accordingly

2024-06-14 21:23 UTC, krrishdholakia commented on litellm/llms/vertex_ai_anthropic.py
> +                json_obj = json.load(open(vertex_credentials))
example for intended flow - 

https://github.com/BerriAI/litellm/blob/056913fd7049923a106130b02d7c29e7f312beec/litellm/tests/test_amazing_vertex_completion.py#L130

2024-06-14 21:25 UTC, krrishdholakia commented on litellm/llms/vertex_ai_anthropic.py
> +                json_obj = json.load(open(vertex_credentials))
Looking further at the example - do you even need to set this? 

If you have `GOOGLE_APPLICATION_CREDENTIALS` in your env, the vertex ai sdk should automatically be handling this?

2024-06-15 06:16 UTC, hawktang commented
Hi @krrishdholakia, I submit the commit to fit support both flows, which can handle filepath or json string and proceed accordingly

```python
try:
    json_obj = json.loads(vertex_credentials)
except json.JSONDecodeError:
    json_obj = json.load(open(vertex_credentials))
```

When vertex_credentials is a JSON string
![image](https://github.com/BerriAI/litellm/assets/2004071/bd06d44f-cafb-4b7e-af55-1d3d11f80140)

When vertex_credentials is a path
<img width="462" alt="image" src="https://github.com/BerriAI/litellm/assets/2004071/40a02a75-906e-40e3-8d79-f5e03b586c59">

2024-06-19 01:36 UTC, hawktang reviewed
I have add the adaptor as requested

2024-06-19 03:20 UTC, krrishdholakia commented
hey @hawktang can you fix the linting error - LGTM to merge after that!

2024-06-19 06:35 UTC, hawktang commented
Hi @krrishdholakia,

Thank you so much, however it is not a linting error

![image](https://github.com/BerriAI/litellm/assets/2004071/fab6ba66-017e-4f67-a084-b84be7ca63cf)

It is before the flake8, from peotry lock file regeneration.

2024-06-20 01:47 UTC, merged