Adding support for Gradient.ai
BerriAI/litellm pull request #420
Opened 2023-09-21 06:39 UTC by michaelfeil

This PR adds support for the API at gradient.ai

Questions:
- Gradient.ai has no "hardcoded" model names, each model has a unique ID that can be finetuned. Is the implementation correct?

Feedback: (just some thoughts, feel free to ignore)
- It took a bit of time to integrate a new LLM, it could be improved by making the code in "main.py" less redundant. Maybe introduce a "BaseClass" to remove redundancy?
- Testing: I tried to write a test, however i found that none of the other llm providers did that. In langchain, there is the idea of "mock" the "request" library, to test APIs, additionally to integration tests.
- Local ci / pre-commit would  be of large use for: `mypy`, `import sorting`, `ruff`, `pytest`

2023-09-21 16:26 UTC, krrishdholakia commented
Hey @michaelfeil, 

- We have testing for each llm. it's in litellm/litellm/tests, there's multiple tests - test_completions.py, test_streaming.py, etc. 
- Acknowledging the feedback on base class. 
- We already have mypy + pytest for ci. Is there something i'm missing here? open to ideas.

2023-09-21 16:32 UTC, michaelfeil commented
For 3. In addition to the CI, I would reproduce some parts, e.g. mypy, black, isort locally using a pre-commit. 
https://pre-commit.com/

2023-09-21 19:10 UTC, ishaan-jaff commented
@michaelfeil 
- can you elaborate in what we should add in the `BaseClass` 
- which sections felt redundant that we can add to BaseClass

2023-09-21 19:14 UTC, ishaan-jaff commented
tracking the pre-commit issue here: https://github.com/BerriAI/litellm/issues/422

2023-09-26 05:59 UTC, ishaan-jaff commented
hi @michaelfeil sorry for the delay in reviewing this PR - we will review this in the next 24 hrs

2023-09-28 04:03 UTC, ishaan-jaff requested changes
thanks for the awesome work on this! requested some changes

2023-09-28 04:03 UTC, ishaan-jaff commented on docs/my-website/docs/providers/gradient.md
> +os.environ["GRADIENT_ACCESS_TOKEN"] = ""
this needs to follow our standard format, it should be `GRADIENT_API_KEY`

2023-09-28 04:03 UTC, ishaan-jaff commented on docs/my-website/docs/providers/gradient.md
> +    messages=[
where moving towards standardizing to add custom_llm_provider as a prefix on `model`. Can you just set it such that `model="gradient/cc2dafce-9e6e-4a23-a918-cad6ba89e42e_base_ml_model"`

thoughts on this DX ?

2023-09-28 04:03 UTC, ishaan-jaff commented on litellm/llms/gradient.py
> +    if "stream" in optional_params and optional_params["stream"] == True:
do they not support streaming?  if so can you mention that in gradient.md

2023-09-28 04:03 UTC, ishaan-jaff commented on litellm/main.py
> +            if inspect.isgenerator(model_response) or ("stream" in optional_params and optional_params["stream"] == True):
for providers that don't support streaming we usually fake streaming. Can you implement it in this PR please ? 

For all our providers we need to support regular completion calls + streaming(if they don't do streaming then we should fake streaming) + Exception mapping

2023-09-28 04:03 UTC, ishaan-jaff commented on litellm/main.py
> +            if inspect.isgenerator(model_response) or ("stream" in optional_params and optional_params["stream"] == True):
you can check out the Fake streaming implementation we did for sagemaker & palm for this

2023-09-28 04:03 UTC, ishaan-jaff commented on litellm/utils.py
> -        api_key = None
why the large deletion here ? can you undo this

2023-09-28 04:03 UTC, ishaan-jaff commented on litellm/utils.py
> +                    pass
we need fake streaming here

2023-09-28 04:03 UTC, ishaan-jaff commented on litellm/utils.py
> +        optional_params["temperature"] = temperature
don't you have to check if temperature != inf and only in that case set it

2023-10-05 17:51 UTC, krrishdholakia commented
@michaelfeil any updates on this?

2023-10-10 14:05 UTC, krrishdholakia commented
closing as there are no updates here

2023-10-10 14:05 UTC, closed without merging