Proxy (health endpoints): Add `/health/db endpoint` w/ Prisma metrics
BerriAI/litellm pull request #4660
Opened 2024-07-11 19:54 UTC by msabramo

We recently had some issues with our LiteLLM Proxy that were caused by us exceeding the number of open connections to our Postgres server (in part because we run multiple instances of the LiteLLM Proxy and in part because we have a couple of other apps using the same Postgres server).

This PR adds a new `/health/db` endpoint to the LiteLLM Proxy that will return information about the database, including metrics from Prisma like the number of open connections. This will allow us to monitor the number of open connections to our database and take action if we exceed the limit.

```shell
$ curl -sSL 'http://0.0.0.0:4000/health/db' | jq '.'
{
  "metrics": {
    "counters": [
      {
        "key": "prisma_client_queries_total",
        "value": 8,
        "labels": {},
        "description": "The total number of Prisma Client queries executed"
      },
      {
        "key": "prisma_datasource_queries_total",
        "value": 13,
        "labels": {},
        "description": "The total number of datasource queries executed"
      },
      {
        "key": "prisma_pool_connections_closed_total",
        "value": 0,
        "labels": {},
        "description": "The total number of pool connections closed"
      },
      {
        "key": "prisma_pool_connections_opened_total",
        "value": 2,
        "labels": {},
        "description": "The total number of pool connections opened"
      }
    ],
    "gauges": [
      {
        "key": "prisma_client_queries_active",
        "value": 0.0,
        "labels": {},
        "description": "The number of currently active Prisma Client queries"
      },
      {
        "key": "prisma_client_queries_wait",
        "value": 0.0,
        "labels": {},
        "description": "The number of datasource queries currently waiting for an free connection"
      },
      {
        "key": "prisma_pool_connections_busy",
        "value": 0.0,
        "labels": {},
        "description": "The number of pool connections currently executing datasource queries"
      },
      {
        "key": "prisma_pool_connections_idle",
        "value": 100.0,
        "labels": {},
        "description": "The number of pool connections that are not busy running a query"
      },
      {
        "key": "prisma_pool_connections_open",
        "value": 2.0,
        "labels": {},
        "description": "The number of pool connections currently open"
      }
    ],
    "histograms": [
      {
        "key": "prisma_client_queries_duration_histogram_ms",
        "value": {
          "sum": 24731.272958,
          "count": 8,
          "buckets": [
            ...
          ]
        },
        "labels": {},
        "description": "The distribution of the time Prisma Client queries took to run end to end"
      },
      {
        "key": "prisma_client_queries_wait_histogram_ms",
        "value": {
          "sum": 0.024627,
          "count": 9,
          "buckets": [
            ...
          ]
        },
        "labels": {},
        "description": "The distribution of the time all datasource queries spent waiting for a free connection"
      },
      {
        "key": "prisma_datasource_queries_duration_histogram_ms",
        "value": {
          "sum": 24804.927917,
          "count": 13,
          "buckets": [
            ...
          ]
        },
        "labels": {},
        "description": "The distribution of the time datasource queries took to run"
      }
    ]
  },
  "db_health_status": {
    "status": "connected",
    "last_updated": "2024-07-11T12:46:35.904744"
  }
}
```

## Title

## Relevant issues

## Type

🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
📖 Documentation
🚄 Infrastructure
✅ Test

## Changes

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

2024-07-11 22:05 UTC, ishaan-jaff commented
FYI I'd recommend setting a connection_limit @msabramo https://docs.litellm.ai/docs/proxy/configs#configure-db-pool-limits--connection-timeouts

2024-07-11 22:06 UTC, ishaan-jaff requested changes
lgtm - can you add a test (`test_health_liveness.py` has an example)

2024-07-11 23:30 UTC, msabramo commented
> FYI I'd recommend setting a connection_limit @msabramo https://docs.litellm.ai/docs/proxy/configs#configure-db-pool-limits--connection-timeouts

Yeah we recently added:

```yaml
database_connection_pool_limit: 10
```

because the default is 100.

2024-07-12 04:16 UTC, krrishdholakia commented
hey @msabramo @ishaan-jaff isn't this similar to our existing `/health/services` endpoint? 

Wondering if this should just exist within that

https://github.com/BerriAI/litellm/blob/b2e46086dda74173ebbe061097055cc4a3930168/litellm/proxy/health_endpoints/_health_endpoints.py#L55

2024-07-12 04:39 UTC, ishaan-jaff commented
> Wondering if this should just exist within that

+1 in favor of adding this to /health/services

2025-04-22 22:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BerriAI/litellm?pullRequest=4660) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BerriAI/litellm?pullRequest=4660) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BerriAI/litellm?pullRequest=4660) it.</sub>

2025-06-07 18:39 UTC, msabramo commented
Closing because LiteLLM should migrate off Prisma

2025-06-07 18:39 UTC, closed without merging