Add the "stop" parameter to the mistral API interface
BerriAI/litellm pull request #5253
Opened 2024-08-16 23:33 UTC by the-crypt-keeper

## Title

Add the "stop" parameter to the mistral API interface

## Type

🐛 Bug Fix

## Changes

The "stop" parameter was not being supported by the mistral API interface, but it's actually available so this PR adds it in.

2024-08-16 23:38 UTC, ishaan-jaff requested changes
could u add a test for this too @the-crypt-keeper ? 

you can use MagicMock to assert the correct params are received

2024-08-17 00:05 UTC, the-crypt-keeper commented
@ishaan-jaff sure! there has also been a `min_tokens` parameter added to this interface, which is related to `stop` (it's the minimum number of tokens to generate before stop applies) - does it make sense to include it in this PR as well?

2024-08-17 00:14 UTC, ishaan-jaff commented
yes - as long as testing is added on this PR

2024-08-17 00:40 UTC, krrishdholakia commented
wouldn't min_tokens work without mod? @the-crypt-keeper  - https://docs.litellm.ai/docs/completion/provider_specific_params#proxy-usage

any non-openai param is assumed to be provider-specific and passed as is in the request body

2024-08-21 22:40 UTC, merged