Added Opik logging and evaluation
BerriAI/litellm pull request #5680
Opened 2024-09-13 12:26 UTC by dsblank

## Title

Added Comet's Opik open-source integration for logging and evaluation. 

For more information on Opik, see: https://github.com/comet-ml/opik

Hope you find this useful!

## Type

🆕 New Feature

## Changes

1. Adds documentation: docs/my-website/docs/observability/opik_integration.md
2. Lists Opik in sidebar
3. Adds the integration: litellm/integrations/opik.py
4. Adds tests: litellm/tests/test_opik.py

## Testing

All Tests Pass:

```
# Set api keys in environment
pytest litellm/tests/test_opik.py
```

![Screenshot from 2024-09-13 08-18-16](https://github.com/user-attachments/assets/7082097d-aee8-40f4-903a-f0e0f49aa5b1)

Tests can run with openai and anthropic keys. Traces and spans are logged to a local or hosted Opik server.

2024-09-13 14:59 UTC, krrishdholakia commented
Hi @dsblank is Opik otel compatible? 

If so, we already have an otel logger - could you just inherit from / use that? (it'll mean fewer dependencies on litellm docker images) 

https://github.com/BerriAI/litellm/blob/cd8d7ca9156a5fc2510db1ef0d43956d3239eccf/litellm/integrations/opentelemetry.py#L41

2024-09-13 16:14 UTC, dsblank commented
@krrishdholakia, I'm checking to be 100% sure, but I don't think so.

2024-09-16 11:25 UTC, dsblank commented
@krrishdholakia , no sorry: opik is not OTEL compatible.

Let me know if there is anything else you need.

2024-09-19 20:01 UTC, dsblank commented
Just checking if you need any further information.

BTW, we had the official Opik launch! https://www.comet.com/site/products/opik/

2024-10-01 15:08 UTC, ishaan-jaff requested changes
requested changes @dsblank

2024-10-01 15:08 UTC, ishaan-jaff commented on litellm/litellm_core_utils/litellm_logging.py
> +opikLogger = None
we're moving away from adding loggers like this to litellm_logging.py - please make use of the CustomLogger() class. See `langsmith.py` on how we implement custom loggers

2024-10-01 15:08 UTC, ishaan-jaff commented on litellm/litellm_core_utils/litellm_logging.py
> +                    if callback == "opik":
there should be no code in `litellm_logging.py`

2024-10-01 15:08 UTC, ishaan-jaff commented on litellm/integrations/opik.py
> +def get_current_trace_id(metadata: Dict[str, Any]) -> str:
these are utils functions. Please make a folder called optik/ 

use this structure:

optik/utils.py -> place optik utils here 
optik/optik.py -> place main logging code here

2024-10-01 15:08 UTC, ishaan-jaff commented on litellm/integrations/opik.py
> +class OpikLogger():
should inherit from litellm.CustomLogger()

2024-10-01 15:08 UTC, ishaan-jaff commented on litellm/integrations/opik.py
> +    def log_event(
you just need to implement async_log_success_event and log_success_event. See langsmith.py or datadog.py as a reference @dsblank

2024-10-01 15:08 UTC, ishaan-jaff commented on litellm/integrations/opik.py
> +    from opik.opik_context import get_current_trace_data
can you implement this without the `optik` python package. Our users complain integrations don't work when they require additional dependencies. 

You can see how we do httpx logging in langsmith or datadog.py

2024-10-01 15:23 UTC, dsblank commented
Thanks for the information on your changing approach! I'll take a look.

2024-10-02 16:02 UTC, merged

2024-10-02 16:39 UTC, jverre commented
@krrishdholakia This ended up being a branch with no changes, I'm currently working on re-writting the integration so that it doesn't depend on the Opik SDK and use the new approach to using loggers in LiteLLM. It will be ready later today for your review

2024-10-03 18:08 UTC, ishaan-jaff commented
can you open a new PR with the feedback we gave @jverre