Add gemini-1.5-pro-002 and gemini-1.5-flash-002
BerriAI/litellm pull request #5879
Opened 2024-09-25 03:40 UTC by ushuz

## Title

Add gemini-1.5-pro-002 and gemini-1.5-flash-002

## Relevant issues

## Type

📖 Documentation
🚄 Infrastructure

## Changes

Add gemini-1.5-pro-002 and gemini-1.5-flash-002

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

N/A

2024-09-25 09:32 UTC, pedroallenrevez commented
please emrege

2024-09-26 02:15 UTC, Manouchehri requested changes

2024-09-26 02:15 UTC, Manouchehri commented on model_prices_and_context_window.json
> +        "max_input_tokens": 1000000,
Shouldn't this be 2097152?

https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#gemini-1.5-pro

2024-09-26 02:15 UTC, Manouchehri commented on model_prices_and_context_window.json
> +        "max_input_tokens": 1000000,
1048576 I think?

https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#gemini-1.5-flash

2024-09-26 02:31 UTC, merged

2024-09-26 02:34 UTC, krrishdholakia commented
Fixed here - https://github.com/BerriAI/litellm/commit/39c9150e975d2ea1218a33349a499d837b288c4f @Manouchehri

2024-09-26 02:52 UTC, SmartManoj commented
`gemini/gemini-1.5-flash-8b-exp-0924` is missing

2024-09-26 04:50 UTC, krrishdholakia commented
@SmartManoj addressed here - https://github.com/BerriAI/litellm/commit/5bc5eaff8a28a1c452bf61e0f3d8f802b7f3e28b