deepinfra: Add supported models
BerriAI/litellm pull request #638
Opened 2023-10-18 16:50 UTC by ichernev

This is necesary when used with llama_index (for example) which checks if model is chat or not, and modifies the input accordingly.

I know the pending llama_index change that won't need the `is_chat_model` functionality: https://github.com/run-llama/llama_index/pull/7885 but then why have all models of each vendor here, either drop it or add `deepinfra` as wel.

2023-10-18 17:02 UTC, ishaan-jaff requested changes

2023-10-18 17:02 UTC, ishaan-jaff commented on litellm/__init__.py
> +    "deepinfra/meta-llama/Llama-2-7b-chat-hf",
we're moving to tracking the models in https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json#L574 

You should not add the models to __init__.py

2023-10-18 17:02 UTC, ishaan-jaff commented on litellm/__init__.py
> +    "deepinfra/meta-llama/Llama-2-7b-chat-hf",
instead you should add the models to the JSON and then read them 

see: https://github.com/BerriAI/litellm/blob/0c090e3675610ce731081529a0a3b8302275f7c3/litellm/__init__.py#L99-L127

2023-10-20 08:31 UTC, ichernev commented on litellm/__init__.py
> +    "deepinfra/meta-llama/Llama-2-7b-chat-hf",
Fixed the price for llama 70b and added the json loading (+ using the loaded list in the right places).

2023-10-20 16:10 UTC, ishaan-jaff approved these changes

2023-10-20 16:10 UTC, merged