Pass timeout to Sagemaker LLM/Databricks
BerriAI/litellm pull request #6697
Opened 2024-11-11 18:48 UTC by njbrake

## Title
Add the timeout parameter to the sagemaker_LLM call

## Relevant issues

## Type

🐛 Bug Fix

## Changes
Pass the timeout parameter to the sagemaker llm

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes
N/A

2024-11-11 19:24 UTC, ishaan-jaff requested changes
hi @njbrake  - could you send a screenshot of a working request after this change ? (Ideally could you show the timeout being passed to sagemaker too)

2024-11-11 19:34 UTC, njbrake commented
@ishaan-jaff  sure thing! Is this what you're looking for? Passing the timeout parameter is using an existing parameter that is already in the `SagemakerLLM` class but wasn't being used. This screenshot is showing how I set the timeout to be 600 and it is now running and being passed into the class as expected.


<img width="1135" alt="Screenshot 2024-11-11 at 2 31 39 PM" src="https://github.com/user-attachments/assets/c054327d-fc9a-4325-8d7e-e6345b5279a2">

2024-11-11 19:43 UTC, ishaan-jaff commented
@njbrake actually i'm looking for a working LLM API call through litellm with this change

2024-11-11 19:46 UTC, njbrake commented
> @njbrake actually i'm looking for a working LLM API call through litellm with this change

@ishaan-jaff  I'm using litellm integrated inside [docetl](https://github.com/ucbepic/docetl), it is working but I don't know how show that it is working via a screenshot.

2024-11-11 19:51 UTC, ishaan-jaff commented
can you set `litellm.set_verbose=True` and then send a screenshot of the server logs

2024-11-11 20:43 UTC, njbrake commented
> can you set `litellm.set_verbose=True` and then send a screenshot of the server logs


Hmm. I set

```
litellm.set_verbose = True
os.environ["LITELLM_LOG"] = "DEBUG"
```
But the the only thing printed to the console is the request, no response gets printed to the console. I know it is working because when I have it in a debugger I can see the success.  How about this screenshot which shows that the timeout parameter was passed through the function and successfully resulted in 145 generated completion tokens?

<img width="797" alt="Screenshot 2024-11-11 at 3 42 32 PM" src="https://github.com/user-attachments/assets/92ce80b9-2c56-48f6-ac3e-051fb0c6b145">

2024-11-13 02:37 UTC, ishaan-jaff approved these changes
LGTM - will merge once main is stable

2025-04-23 00:46 UTC, closed without merging