fixes for chat completion impl
BerriAI/litellm pull request #6981
Opened 2024-12-02 08:18 UTC by raspawar

## Nvidia Integration Fixes

2024-12-16 15:25 UTC, mattf requested changes
please update to maintain backward compat

2024-12-16 15:25 UTC, mattf commented on litellm/__init__.py
> -    "nvidia_nim",
people have been using "nvidia_nim". instead of removing it, can it be an alias for "nvidia"?

2024-12-16 15:25 UTC, mattf commented on litellm/litellm_core_utils/get_llm_provider_logic.py
> +                or get_secret("NVIDIA_API_BASE")
we're using `NVIDIA_BASE_URL` in other frameworks. `*_API_BASE` appears idiomatic for litellm. can we do both?

2024-12-16 15:25 UTC, mattf commented on litellm/litellm_core_utils/get_llm_provider_logic.py
> +            dynamic_api_key = api_key or get_secret_str("NVIDIA_API_KEY")
add backward compat for `NVIDIA_NIM_API_KEY`

2024-12-16 15:25 UTC, mattf commented on litellm/litellm_core_utils/get_llm_provider_logic.py
> +                or get_secret("NVIDIA_API_BASE")
also keep backward compat w/ `NVIDIA_NIM_API_BASE`

2024-12-19 19:01 UTC, joaomdmoura commented
+1 
@mattf We could definitely use this 🙏 lmk if there is anything I cna do to get it merged

2024-12-19 19:08 UTC, ishaan-jaff commented
hi we already have `nvidia_nim` support - what exactly is the issue ? 

Can I see a example request to repro the issue @raspawar  ?

2024-12-19 19:09 UTC, ishaan-jaff commented
@joaomdmoura  - what provider / model are you waiting on us to add support for ? 

(python code would help so we can validate)

2024-12-19 19:26 UTC, raspawar commented
Hi @ishaan-jaff, I am Rashmi from NVIDIA.
Thanks for the integration and the existing integration works perfectly fine! 
This PR extends support to :
- parameters NVIDIA_API_KEY, provider=nvidia, etc. to maintain the uniform setup for nvidia endpoints across multiple frameworks. 
- Model validation, checking available models through NvidiaConfig().available_models()
- test case coverage and more

2024-12-19 21:31 UTC, joaomdmoura commented
hey @ishaan-jaff thanks for the answer! It's exactly what @raspawar said, I'm building a crew that uses nvidia so this will come super in handy :)

2025-01-17 14:57 UTC, raspawar commented
@ishaan-jaff ptal

2025-01-28 06:02 UTC, raspawar commented
@krrishdholakia would you be able to review changes in this PR too? Thanks in advance!

2025-02-22 15:06 UTC, mattf requested changes
pls resolve conflicts

2025-03-10 01:46 UTC, ghost commented
Hi @raspawar, thank you for your work. Currently your PR does not follow the conventions for an LLM integration. 

For example - your folder structure needs to be `<provider>/<endpoint>/transformation.py` 

Since your PR seems to be openai-compatible, you can see vllm for reference - 

https://github.com/BerriAI/litellm/tree/e00d4fb18c2fe8400cc949bf8afb64e38e8f3927/litellm/llms/hosted_vllm

2025-03-10 01:48 UTC, ghost commented on litellm/main.py
> +            or custom_llm_provider == "nvidia"
there is no need to hardcode this here. just add it as an `openai_compatible_provider` in `__init__.py`

2025-03-10 01:48 UTC, krrishdholakia commented on litellm/main.py
> +        print(e, model, custom_llm_provider)
please remove any print statements

2025-03-10 01:48 UTC, krrishdholakia commented on litellm/main.py
> +            or custom_llm_provider == "nvidia"
same here - no need to hardcode this

2025-03-10 01:48 UTC, krrishdholakia commented on litellm/main.py
> +            or custom_llm_provider == "nvidia"
same here, no need to hardcode this

2025-03-10 01:49 UTC, krrishdholakia commented on litellm/utils.py
> +            print("error", e)
please remove any print statements

2025-03-10 01:50 UTC, krrishdholakia commented on litellm/utils.py
> +    elif custom_llm_provider in ["nvidia_nim", "nvidia"]:
make set

2025-03-10 01:51 UTC, krrishdholakia commented on litellm/utils.py
> +        optional_params = litellm.nvidiaEmbeddingConfig.map_openai_params(
this is wrong. 

nvidia_nim and nvidia are 2 separate providers. 

the optional param translation should be handled separately for them.

2025-03-10 01:51 UTC, krrishdholakia commented on litellm/utils.py
> +            and custom_llm_provider != "nvidia"
remove this hardcoding, it's sufficient to add to `openai_compatible_providers` on init.py

2025-03-10 01:52 UTC, krrishdholakia commented on litellm/utils.py
> +                missing_keys.append("NVIDIA_API_KEY")
does nvidia_nim also accept `NVIDIA_API_KEY`?

2025-03-10 01:53 UTC, krrishdholakia commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
i'm confused 

nvidia_nim is a separate provider to nvidia, why is the import for nvidia nim config coming from nvidia?

2025-03-10 02:15 UTC, raspawar commented on litellm/utils.py
> +                missing_keys.append("NVIDIA_API_KEY")
Yes

2025-03-10 02:16 UTC, raspawar commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
No, just keeping naming consistent

2025-03-10 02:20 UTC, raspawar commented on litellm/utils.py
> +        optional_params = litellm.nvidiaEmbeddingConfig.map_openai_params(
No they are same, keeping naming consistent.

2025-03-10 02:23 UTC, krrishdholakia commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
so is nvidia nim inside nvidia folder? 

this breaks the pattern for `llms/` where the provider name is the folder - https://github.com/BerriAI/litellm/tree/main/litellm/llms
<img width="1351" alt="Screenshot 2025-03-09 at 7 23 07 PM" src="https://github.com/user-attachments/assets/bd45241c-138c-4692-bd05-2601fa2c9486" />

2025-03-10 02:26 UTC, raspawar commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
updating the folder structure as you suggested and renaming NvidiaNimConfig to NvidiaConfig

2025-03-10 02:28 UTC, krrishdholakia commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
was there an older nvidianim config? if so - what happens to it? 

I'm unclear on whether you're modifying the existing - `nvidia_nim/` integration, or adding a new provider

if it's a new provider, can we avoid any modification of the existing `nvidia_nim/` provider

2025-03-10 02:30 UTC, raspawar commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
I am updating existing nvidia_nim integration. Will add Readme.md file with a note.

2025-03-11 06:04 UTC, raspawar commented on tests/llm_translation/test_max_completion_tokens.py
> +    from litellm.llms.nvidia.chat import NvidiaNimConfig
I have addressed all review changes, can we close this @krrishdholakia ?

2025-03-17 09:36 UTC, raspawar commented
Hey @krrishdholakia, @ishaan-jaff, just following up on this PR. It's been a couple of months, and it'd be great to get it merged soon so we don’t have to keep resolving conflicts. Let me know if there’s anything blocking it.

cc: @dglogo
Thanks!

2025-04-22 22:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BerriAI/litellm?pullRequest=6981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BerriAI/litellm?pullRequest=6981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BerriAI/litellm?pullRequest=6981) it.</sub>

2025-04-22 22:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BerriAI/litellm?pullRequest=6981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BerriAI/litellm?pullRequest=6981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BerriAI/litellm?pullRequest=6981) it.</sub>

2025-04-22 22:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BerriAI/litellm?pullRequest=6981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/BerriAI/litellm?pullRequest=6981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BerriAI/litellm?pullRequest=6981) it.</sub>

2025-07-29 00:04 UTC, closed without merging