fix OR deepseek
BerriAI/litellm pull request #7425
Opened 2024-12-26 15:10 UTC by paul-gauthier

OpenRouter no longer supports the .../deepseek-coder endpoint, only .../deepseek-chat.

2024-12-27 22:36 UTC, ishaan-jaff requested changes
reviewed

2024-12-27 22:36 UTC, ishaan-jaff commented on model_prices_and_context_window.json
> -    "openrouter/deepseek/deepseek-coder": {
can you not delete the model, instead add a new model 

context - deleting the model has a risk of breaking existing user code

2024-12-28 16:37 UTC, ishaan-jaff approved these changes
LGTM

2024-12-28 16:37 UTC, ishaan-jaff commented
good to merge @paul-gauthier ?

2024-12-28 17:07 UTC, paul-gauthier commented
Yes.

2024-12-29 01:08 UTC, merged