Refresh VoyageAI models, prices and context
BerriAI/litellm pull request #7472
Opened 2024-12-30 10:53 UTC by fzowl

## Title

Refresh VoyageAI models, prices and context based on the documentation available at

https://docs.voyageai.com/docs/pricing
https://docs.voyageai.com/docs/embeddings
https://docs.voyageai.com/docs/reranker

## Type

Model refresh

## Changes

Refresh VoyageAI models, prices and context. I removed the old models and added the new models.

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locally
If UI changes, send a screenshot/GIF of working UI fixes

I did not test the change

2025-01-01 22:12 UTC, ishaan-jaff requested changes
reviewed

2025-01-01 22:12 UTC, ishaan-jaff commented on model_prices_and_context_window.json
> -    "voyage/voyage-finance-2": {
same feedback as the last PR - please do not remove the models

2025-01-02 18:45 UTC, fzliu commented on model_prices_and_context_window.json
> +    "voyage/voyage-finance-2": {
@ishaan-jaff `voyage-finance-2` is in this PR.

2025-01-02 18:46 UTC, fzliu commented on model_prices_and_context_window.json
> -    "voyage/voyage-finance-2": {
It's in the PR -- there's just a slight reordering (see my other comment).

2025-01-07 04:37 UTC, ishaan-jaff approved these changes
LGTM

2025-01-07 04:38 UTC, merged