Added statuscode to Bedrock AWS Credentials Missing Error
BerriAI/litellm pull request #758
Opened 2023-11-03 22:25 UTC by ChrisDryden

This error message was missing a status code and was not available to the end user.

2023-11-04 01:15 UTC, ishaan-jaff requested changes

2023-11-04 01:15 UTC, ishaan-jaff commented on litellm/llms/bedrock.py
> +        raise BedrockError(message="AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file", status_code=500)
auth error is usually 401 right ? 

HTTP 401 UNAUTHORIZED

2023-11-04 05:17 UTC, krrishdholakia commented
@ChrisDryden / @ishaan-jaff I believe a fix for this is already in `main` - https://github.com/BerriAI/litellm/blob/4c895d2e91767838b28a66e17fec0f0d66f6d9a8/litellm/llms/bedrock.py#L193

w/ the 401 status code. 

does this cover the purpose of the PR/request? @ChrisDryden

2023-11-05 00:28 UTC, krrishdholakia commented
This is now in prod v`0.13.0`

2023-11-05 00:28 UTC, closed without merging